networks:
  blueboard-network:
    name: blueboard-network

services:
## BOARDLIGHT
  boardlight:
    networks:
      - blueboard-network
    build:
      context: Boardlight/
      dockerfile: ../docker/Dockerfile.boardlight
    ports:
      - 80:80
    volumes:
      - .:/app
      - /app/node_modules

## BLUEBOARD
  blueboard:
    networks:
      - blueboard-network
    build:
      context: ./
      dockerfile: docker/Dockerfile.blueboard
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:5279
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
    ports:
      - "${BLUEBOARD_PORT}:5279"
    restart: unless-stopped
    volumes:
      - blueboard-data:/app

  db:
    networks:
      - blueboard-network
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  blueboard-data:
