FROM node:20-slim
RUN npm install -g pnpm@latest-10
WORKDIR /app
COPY ./Boardlight/package.json /app/
RUN pnpm install
COPY ./openapi_dev /app/
COPY ./Boardlight /app/
WORKDIR /app/Boardlight
EXPOSE 80
CMD pnpm install && pnpm dev --host
