FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY ./LovassyApp.sln ./
COPY ./Blueboard Blueboard/
COPY ./Helpers.WebApi Helpers.WebApi/
COPY ./Helpers.Cryptography Helpers.Cryptography/
COPY ./Helpers.Email Helpers.Email/
WORKDIR /app/Blueboard
EXPOSE 5279
ENTRYPOINT ["dotnet", "watch"]
