FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

# Copy solution, helpers & project files
COPY ./LovassyApp.sln ./
COPY ./Blueboard/Blueboard.csproj Blueboard/
COPY ./Helpers.WebApi/Helpers.WebApi.csproj Helpers.WebApi/
COPY ./Helpers.Cryptography/Helpers.Cryptography.csproj Helpers.Cryptography/
COPY ./Helpers.Cryptography.Tests/Helpers.Cryptography.Tests.csproj Helpers.Cryptography.Tests/
COPY ./Helpers.Email/Helpers.Email.csproj Helpers.Email/

# Restore
RUN dotnet restore

# Copy source code
COPY ./Blueboard Blueboard/
COPY ./Helpers.WebApi Helpers.WebApi/
COPY ./Helpers.Cryptography Helpers.Cryptography/
COPY ./Helpers.Email Helpers.Email/

# Copy control script
COPY docker/blueboard_entrypoint.sh blueboard-ctl.sh
RUN chmod +x blueboard-ctl.sh

WORKDIR /app/Blueboard

ENTRYPOINT ["/app/blueboard-ctl.sh"]
