/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthRefreshResponseUser {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "emailVerifiedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email_verified_at: Option<Option<String>>,
    #[serde(rename = "realName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub real_name: Option<Option<String>>,
    #[serde(rename = "class", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub class: Option<Option<String>>,
}

impl AuthRefreshResponseUser {
    pub fn new() -> AuthRefreshResponseUser {
        AuthRefreshResponseUser {
            id: None,
            name: None,
            email: None,
            email_verified_at: None,
            real_name: None,
            class: None,
        }
    }
}


