/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthCreateUserGroupRequestBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "permissions")]
    pub permissions: Vec<String>,
}

impl AuthCreateUserGroupRequestBody {
    pub fn new(name: String, permissions: Vec<String>) -> AuthCreateUserGroupRequestBody {
        AuthCreateUserGroupRequestBody {
            name,
            permissions,
        }
    }
}


