/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthRefreshResponse {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::AuthRefreshResponseUser>>,
    #[serde(rename = "token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub token: Option<Option<String>>,
    #[serde(rename = "refreshToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<Option<String>>,
    #[serde(rename = "refreshTokenExpiration", skip_serializing_if = "Option::is_none")]
    pub refresh_token_expiration: Option<String>,
}

impl AuthRefreshResponse {
    pub fn new() -> AuthRefreshResponse {
        AuthRefreshResponse {
            user: None,
            token: None,
            refresh_token: None,
            refresh_token_expiration: None,
        }
    }
}


