/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImageVotingsViewImageVotingEntryResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "imageUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<Option<String>>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::ImageVotingsViewImageVotingEntryResponseUser>>,
    #[serde(rename = "imageVotingId", skip_serializing_if = "Option::is_none")]
    pub image_voting_id: Option<i32>,
    #[serde(rename = "canChoose", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub can_choose: Option<Option<bool>>,
    #[serde(rename = "chosen", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub chosen: Option<Option<bool>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ImageVotingsViewImageVotingEntryResponse {
    pub fn new() -> ImageVotingsViewImageVotingEntryResponse {
        ImageVotingsViewImageVotingEntryResponse {
            id: None,
            title: None,
            image_url: None,
            user_id: None,
            user: None,
            image_voting_id: None,
            can_choose: None,
            chosen: None,
            created_at: None,
            updated_at: None,
        }
    }
}


