/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImageVotingsUpdateImageVotingRequestBodyImageVotingAspect {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
}

impl ImageVotingsUpdateImageVotingRequestBodyImageVotingAspect {
    pub fn new(key: String, name: String, description: String) -> ImageVotingsUpdateImageVotingRequestBodyImageVotingAspect {
        ImageVotingsUpdateImageVotingRequestBodyImageVotingAspect {
            key,
            name,
            description,
        }
    }
}


