/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImageVotingsIndexImageVotingsResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "showUploaderInfo", skip_serializing_if = "Option::is_none")]
    pub show_uploader_info: Option<bool>,
    #[serde(rename = "uploaderUserGroupId", skip_serializing_if = "Option::is_none")]
    pub uploader_user_group_id: Option<i32>,
    #[serde(rename = "bannedUserGroupId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub banned_user_group_id: Option<Option<i32>>,
    #[serde(rename = "maxUploadsPerUser", skip_serializing_if = "Option::is_none")]
    pub max_uploads_per_user: Option<i32>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ImageVotingsIndexImageVotingsResponse {
    pub fn new() -> ImageVotingsIndexImageVotingsResponse {
        ImageVotingsIndexImageVotingsResponse {
            id: None,
            name: None,
            description: None,
            r#type: None,
            active: None,
            show_uploader_info: None,
            uploader_user_group_id: None,
            banned_user_group_id: None,
            max_uploads_per_user: None,
            created_at: None,
            updated_at: None,
        }
    }
}


