/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImageVotingsIndexImageVotingEntryImagesRequestBody {
    #[serde(rename = "imageVotingId", skip_serializing_if = "Option::is_none")]
    pub image_voting_id: Option<i32>,
}

impl ImageVotingsIndexImageVotingEntryImagesRequestBody {
    pub fn new() -> ImageVotingsIndexImageVotingEntryImagesRequestBody {
        ImageVotingsIndexImageVotingEntryImagesRequestBody {
            image_voting_id: None,
        }
    }
}


