/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImageVotingsIndexImageVotingChoicesResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "aspectKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub aspect_key: Option<Option<String>>,
    #[serde(rename = "imageVotingId", skip_serializing_if = "Option::is_none")]
    pub image_voting_id: Option<i32>,
    #[serde(rename = "imageVotingEntry", skip_serializing_if = "Option::is_none")]
    pub image_voting_entry: Option<Box<crate::models::ImageVotingsIndexImageVotingChoicesResponseImageVotingEntry>>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<uuid::Uuid>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ImageVotingsIndexImageVotingChoicesResponse {
    pub fn new() -> ImageVotingsIndexImageVotingChoicesResponse {
        ImageVotingsIndexImageVotingChoicesResponse {
            id: None,
            aspect_key: None,
            image_voting_id: None,
            image_voting_entry: None,
            user_id: None,
            created_at: None,
            updated_at: None,
        }
    }
}


