/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImageVotingsIndexImageVotingChoicesResponseImageVotingEntry {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
}

impl ImageVotingsIndexImageVotingChoicesResponseImageVotingEntry {
    pub fn new() -> ImageVotingsIndexImageVotingChoicesResponseImageVotingEntry {
        ImageVotingsIndexImageVotingChoicesResponseImageVotingEntry {
            id: None,
            title: None,
        }
    }
}


