/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImageVotingsCreateImageVotingRequestBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "aspects")]
    pub aspects: Vec<crate::models::ImageVotingsCreateImageVotingRequestBodyImageVotingAspect>,
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "showUploaderInfo")]
    pub show_uploader_info: bool,
    #[serde(rename = "uploaderUserGroupId")]
    pub uploader_user_group_id: i32,
    #[serde(rename = "bannedUserGroupId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub banned_user_group_id: Option<Option<i32>>,
    #[serde(rename = "maxUploadsPerUser")]
    pub max_uploads_per_user: i32,
    #[serde(rename = "superIncrementAllowed")]
    pub super_increment_allowed: bool,
    #[serde(rename = "superIncrementValue")]
    pub super_increment_value: i32,
}

impl ImageVotingsCreateImageVotingRequestBody {
    pub fn new(name: String, description: String, r#type: String, aspects: Vec<crate::models::ImageVotingsCreateImageVotingRequestBodyImageVotingAspect>, active: bool, show_uploader_info: bool, uploader_user_group_id: i32, max_uploads_per_user: i32, super_increment_allowed: bool, super_increment_value: i32) -> ImageVotingsCreateImageVotingRequestBody {
        ImageVotingsCreateImageVotingRequestBody {
            name,
            description,
            r#type,
            aspects,
            active,
            show_uploader_info,
            uploader_user_group_id,
            banned_user_group_id: None,
            max_uploads_per_user,
            super_increment_allowed,
            super_increment_value,
        }
    }
}


