/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImageVotingsViewImageVotingResponseImageVotingAspectEntryIncrement {
    #[serde(rename = "entryId", skip_serializing_if = "Option::is_none")]
    pub entry_id: Option<i32>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
}

impl ImageVotingsViewImageVotingResponseImageVotingAspectEntryIncrement {
    pub fn new() -> ImageVotingsViewImageVotingResponseImageVotingAspectEntryIncrement {
        ImageVotingsViewImageVotingResponseImageVotingAspectEntryIncrement {
            entry_id: None,
            r#type: None,
        }
    }
}


