/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImportIndexUsersResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "omCodeHashed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub om_code_hashed: Option<Option<String>>,
    #[serde(rename = "publicKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<Option<String>>,
}

impl ImportIndexUsersResponse {
    pub fn new() -> ImportIndexUsersResponse {
        ImportIndexUsersResponse {
            id: None,
            om_code_hashed: None,
            public_key: None,
        }
    }
}


