/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchoolIndexGradesResponse {
    #[serde(rename = "subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Option<String>>,
    #[serde(rename = "grades", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub grades: Option<Option<Vec<crate::models::SchoolIndexGradesResponseGrade>>>,
}

impl SchoolIndexGradesResponse {
    pub fn new() -> SchoolIndexGradesResponse {
        SchoolIndexGradesResponse {
            subject: None,
            grades: None,
        }
    }
}


