/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShopUpdateLoloRequestRequestBody {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "body")]
    pub body: String,
}

impl ShopUpdateLoloRequestRequestBody {
    pub fn new(title: String, body: String) -> ShopUpdateLoloRequestRequestBody {
        ShopUpdateLoloRequestRequestBody {
            title,
            body,
        }
    }
}


