/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShopIndexOwnLolosResponseCoin {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<uuid::Uuid>,
    #[serde(rename = "isSpent", skip_serializing_if = "Option::is_none")]
    pub is_spent: Option<bool>,
    #[serde(rename = "loloType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lolo_type: Option<Option<String>>,
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
    #[serde(rename = "grades", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub grades: Option<Option<Vec<crate::models::ShopIndexOwnLolosResponseGrade>>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ShopIndexOwnLolosResponseCoin {
    pub fn new() -> ShopIndexOwnLolosResponseCoin {
        ShopIndexOwnLolosResponseCoin {
            id: None,
            user_id: None,
            is_spent: None,
            lolo_type: None,
            reason: None,
            grades: None,
            created_at: None,
            updated_at: None,
        }
    }
}


