/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShopOverruleLoloRequestRequestBody {
    #[serde(rename = "accepted")]
    pub accepted: bool,
    #[serde(rename = "loloAmount", skip_serializing_if = "Option::is_none")]
    pub lolo_amount: Option<i32>,
}

impl ShopOverruleLoloRequestRequestBody {
    pub fn new(accepted: bool) -> ShopOverruleLoloRequestRequestBody {
        ShopOverruleLoloRequestRequestBody {
            accepted,
            lolo_amount: None,
        }
    }
}


