/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShopIndexOwnLoloRequestsResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body: Option<Option<String>>,
    #[serde(rename = "acceptedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accepted_at: Option<Option<String>>,
    #[serde(rename = "deniedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub denied_at: Option<Option<String>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ShopIndexOwnLoloRequestsResponse {
    pub fn new() -> ShopIndexOwnLoloRequestsResponse {
        ShopIndexOwnLoloRequestsResponse {
            id: None,
            title: None,
            body: None,
            accepted_at: None,
            denied_at: None,
            created_at: None,
            updated_at: None,
        }
    }
}


