/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShopCreateOwnedItemRequestBody {
    #[serde(rename = "userId")]
    pub user_id: uuid::Uuid,
    #[serde(rename = "productId")]
    pub product_id: i32,
    #[serde(rename = "usedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub used_at: Option<Option<String>>,
}

impl ShopCreateOwnedItemRequestBody {
    pub fn new(user_id: uuid::Uuid, product_id: i32) -> ShopCreateOwnedItemRequestBody {
        ShopCreateOwnedItemRequestBody {
            user_id,
            product_id,
            used_at: None,
        }
    }
}


