/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShopViewOwnedItemResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<uuid::Uuid>,
    #[serde(rename = "product", skip_serializing_if = "Option::is_none")]
    pub product: Option<Box<crate::models::ShopViewOwnedItemResponseProduct>>,
    #[serde(rename = "usedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub used_at: Option<Option<String>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ShopViewOwnedItemResponse {
    pub fn new() -> ShopViewOwnedItemResponse {
        ShopViewOwnedItemResponse {
            id: None,
            user_id: None,
            product: None,
            used_at: None,
            created_at: None,
            updated_at: None,
        }
    }
}


