/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShopUpdateProductRequestBodyInput {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "label")]
    pub label: String,
}

impl ShopUpdateProductRequestBodyInput {
    pub fn new(r#type: String, key: String, label: String) -> ShopUpdateProductRequestBodyInput {
        ShopUpdateProductRequestBodyInput {
            r#type,
            key,
            label,
        }
    }
}


