/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShopUpdateLoloRequestCreatedNotifiersRequestBody {
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
}

impl ShopUpdateLoloRequestCreatedNotifiersRequestBody {
    pub fn new(emails: Vec<String>) -> ShopUpdateLoloRequestCreatedNotifiersRequestBody {
        ShopUpdateLoloRequestCreatedNotifiersRequestBody {
            emails,
        }
    }
}


