/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShopCreateLoloRequestResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body: Option<Option<String>>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<uuid::Uuid>,
    #[serde(rename = "acceptedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accepted_at: Option<Option<String>>,
    #[serde(rename = "deniedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub denied_at: Option<Option<String>>,
}

impl ShopCreateLoloRequestResponse {
    pub fn new() -> ShopCreateLoloRequestResponse {
        ShopCreateLoloRequestResponse {
            id: None,
            title: None,
            body: None,
            user_id: None,
            accepted_at: None,
            denied_at: None,
        }
    }
}


