/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShopCreateQrCodeRequestBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email")]
    pub email: String,
}

impl ShopCreateQrCodeRequestBody {
    pub fn new(name: String, email: String) -> ShopCreateQrCodeRequestBody {
        ShopCreateQrCodeRequestBody {
            name,
            email,
        }
    }
}


