/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StatusNotifyOnResetKeyPasswordSetRequestBody {
    #[serde(rename = "email")]
    pub email: String,
}

impl StatusNotifyOnResetKeyPasswordSetRequestBody {
    pub fn new(email: String) -> StatusNotifyOnResetKeyPasswordSetRequestBody {
        StatusNotifyOnResetKeyPasswordSetRequestBody {
            email,
        }
    }
}


