/*
 * Blueboard
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsersUpdateUserRequestBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "userGroups")]
    pub user_groups: Vec<i32>,
}

impl UsersUpdateUserRequestBody {
    pub fn new(name: String, email: String, user_groups: Vec<i32>) -> UsersUpdateUserRequestBody {
        UsersUpdateUserRequestBody {
            name,
            email,
            user_groups,
        }
    }
}


