name: Blueboard Build
run-name: ${{ github.actor }} is doing a development build of Blueboard 🚀
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env: 
      ASPNETCORE_ENVIRONMENT: development
    strategy:
      matrix:
        dotnet-version: [ '7.0' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Blueboard dependencies
        run: dotnet restore
      - name: Build Blueboard
        run: dotnet build --configuration Debug --no-restore
      - name: Test Blueboard
        run: dotnet test --no-restore --verbosity normal
      - name: Commit new schema
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          file_pattern: openapi_dev/schema.json
          commit_message: Updated the API schema
          