name: Boardlight Build
run-name: ${{ github.actor }} is doing a development build of Boardlight 🚀
on:
  workflow_run:
    workflows: ["Blueboard Build"]
    branches: [master]
    types:
      - completed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false
      - name: Install Boardlight dependencies
        run: |
          cd Boardlight
          pnpm install --no-frozen-lockfile
      - name: Generate Typescript API Client
        run: |
            cd Boardlight
            pnpm generate-api-client
      - name: Build Boardlight
        run: |
          cd Boardlight
          pnpm build
      - name: Commit new API Client
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: Boardlight/src/api/generated/**
          commit_message: Updated the Typescript API client for Boardlight
