name: Boardlight Build
run-name: ${{ github.actor }} is doing a development build of Boardlight 🚀
on:
  workflow_run:
    workflows: ["Blueboard Build"]
    branches: [master]
    types:
      - completed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Boardlight dependencies
        run: |
          cd Boardlight
          pnpm install --no-frozen-lockfile
      - name: Build Boardlight
        run: |
          cd Boardlight
          pnpm build
      - name: Generate Typescript API Client
        run: |
            cd Boardlight
            pnpm generate-api-client
      - name: Verify changed files
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: |
            Boardlight/src/api/generated/**
      - name: Commit new schema
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Updated the Typescript API client for Boardlight"
      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          