name: Blueboard Change Tracking Marker
on:
  workflow_run:
    workflows: [ "Application Stack Deploy" ]
    branches: [ master ]
    types:
      - completed

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Set Appsettings Var
        id: set_var
        run: |
          content=`cat ./Blueboard/appsettings.Production.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=appsettings::$content"
      # This step builds a var with the release tag value to use later
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${{ fromJson(steps.set_var.outputs.appsettings).Status.Version }}" >> $GITHUB_ENV
      # This step creates a new Change Tracking Marker
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          version: "${{ env.RELEASE_VERSION }}"
          user: "${{ github.actor }}"
          region: EU